### ISSUE TITLE
大佬是用什么编译器的呀？看了你用CMake，想请教一下是不是也要熟悉一下cmake的语法？

### ISSUE THREAD

**Issue by imsjz** [Light-City/offerInterviewGuide#1]
gcc编译，是的，我用Clion构建。我怀疑你isue开错地方了，应该在那个c++那些事项目吧，哈哈。

**Comment by Light-City** [comment]
> gcc编译，是的，我用Clion构建。我怀疑你isue开错地方了，应该在那个c++那些事项目吧，哈哈。

尽量用g++，issue没开错地方，因为一开始我用的vim写的，所以纯g++，后来用编译器CLion，部分有CMakeLists.txt文件，直接导入就行，后面会更新这个文件包含整个项目，持续关注~

**Comment by Light-City** [comment]
> gcc编译，是的，我用Clion构建。我怀疑你isue开错地方了，应该在那个c++那些事项目吧，哈哈。

**Comment by Light-City** [comment]
熟悉一下最好~
